version: '3'
services:
    telegraf:
        image: telegraf
        depends_on:
          - influxdb
        volumes:
          - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        ports:
            - 57000:57000

    influxdb:
        image: influxdb
        volumes:
          - ./influxdb:/var/lib/influxdb
          - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
        ports:
            - 8086:8086

    chronograf:
        image: chronograf:alpine
        command: --influxdb-url=http://influxdb:8086
        volumes:
          - ./chronograf:/var/lib/chronograf
        ports:
            - 8888:8888
